### ISSUE TITLE
no conditional compilation (cfg) support for hardware tasks

### ISSUE THREAD

**Issue by japaric** [rtic-rs/cortex-m-rtic#463]
this fails to compile with cortex-m-rtic 0.5.6

``` rust
#[rtic::app(device = nrf52840_hal::pac)]
const APP: () = {
    #[cfg(feature = "my-feature")]
    #[task(binds = RNG)]
    fn rng(_: rng::Context) {}
};
```

with this error message

``` text
error[E0423]: expected function, found module `crate::rng`
```

**Comment by japaric** [comment]
looking at the expanded code

``` rust
    #[no_mangle]
    unsafe fn RNG() {
        const PRIORITY: u8 = 1u8;
        rtic::export::run(PRIORITY, || {
            crate::rng(rng::Context::new(&rtic::export::Priority::new(PRIORITY)))
        });
    }
```

this interrupt handler should have a `cfg`
